apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-deployment
  labels:
    apptype: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      name: nova-nginx-webapp
      labels:
        app: web
    spec:
      containers:
        - name: nginx-pod
          image: nginx