apiVersion: v1
kind: Pod
metadata:
  name: pod-with-envvariable
spec:
  containers:
    - name: sample-app
      image: busybox
      ports:
        - containerPort: 80
      env:
        - name: THEME
          value: dark