apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app.kubernetes.io/name: nova-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.0.171.239